apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-book
  labels:
    app: kafka-book
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-book
  template:
    metadata:
      labels:
        app: kafka-book
    spec:
      containers:
        - name: kafka-book
          image: confluentinc/cp-kafka:7.0.1
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://kafka-book:29092,EXTERNAL://kafka-book.default.svc.cluster.local:9092"
            - name: KAFKA_LISTENERS
              value: "PLAINTEXT://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper.default.svc.cluster.local:2181"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-book
spec:
  selector:
    app: kafka-book
  ports:
    - name: external
      port: 9092
      targetPort: 9092
    - name: internal
      port: 29092
      targetPort: 29092