apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      name: user-service
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: dariyush1/libraryappmicroservice-user-service
          imagePullPolicy: IfNotPresent
          env:
            - name: SPRING_CLOUD_CONSUL_HOST
              value: "consul"
            - name: SPRING_CLOUD_CONSUL_PORT
              value: "8500"
            - name: SPRING_CLOUD_CONSUL_DISCOVERY_HOSTNAME
              value: "user-service.default.svc.cluster.local"
            - name: SPRING_CLOUD_CONSUL_DISCOVERY_PREFER_IP_ADDRESS
              value: "false"
            - name: SPRING_CLOUD_CONSUL_DISCOVERY_HEALTH_CHECK_URL
              value: "http://user-service.default.svc.cluster.local:8082/actuator/health"

            - name: POSTGRES_URL
              value: "jdbc:postgresql://postgres.default.svc.cluster.local:5432/postgres"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8082"
    prometheus.io/path: "/actuator/prometheus"
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
      name: user-service