spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      mvc:
        routes:
          - id: book-service
            uri: lb://book-service
            predicates:
              - Path=/books/**
          - id: image-service
            uri: lb://image-service
            predicates:
              - Path=/images/**
          - id: user-service
            uri: lb://user-service
            predicates:
              - Path=/auth/signIn,/auth/signUp
            # filters:
            #   - CircuitBreaker=myCircuitBreaker,fallbackUri=forward:/fallback

    circuitbreaker:
      resilience4j:
        instances:
          config:
            slidingWindowSize: 5
            failureRateThreshold: 50
            waitDurationInOpenState: 10000
            permittedNumberOfCallsInHalfOpenState: 3
            minimumNumberOfCalls: 5

    consul:
      host: localhost
      port: 8500
      discovery:
        hostname: localhost
        healthCheckUrl: http://localhost:8081/actuator/health

  spring:
    config:
      import:
        - "consul:"
    cloud:
      config:
        discovery:
          enabled: true
          service-id: config

  datasource:
    url: jdbc:postgresql://localhost:5432/users
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: false

  main:
    web-application-type: servlet
    allow-bean-definition-overriding: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.gateway: trace

token:
  signing:
    key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855

  cloud:
    gateway:
      httpclient:
        wiretap: true
      httpserver:
        wiretap: true

resilience4j:
  circuitbreaker:
    instances:
      myCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 3
        failureRateThreshold: 50
        waitDurationInOpenState: 10000