server:
  port: 8081

spring:
  application:
    name: book-service
  config:
    import:
      - "consul:"
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        hostname: localhost
        healthCheckUrl: http://localhost:8081/actuator/health
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always


