 spring:
  application:
    name: image-service
  config:
    import:
      optional:consul:
  cloud:
    config:
      import-check:
        enabled: false
    consul:
      host: localhost
      port: 8500
      config:
        enabled: false
      discovery:
        enabled: false
        hostname: localhost
        health-check-path: /actuator/health
        health-check-interval: 10s
        healthCheckUrl: http://localhost:8082/actuator/health
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  data:
    mongodb:
      uri: mongodb://localhost:27017
      username: mongo
      password: mongo
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB

 server:
  port: 8082

 feign:
   client:
     config:
       default:
         connectTimeout: 5000
         readTimeout: 5000

 management:
   endpoints:
     web:
       exposure:
         include: "*"
   endpoint:
     health:
       show-details: always



