server:
  port: 8084

spring:
  application:
    name: image-service
  cloud:
    consul:
      host: consul
      port: 8500
      discovery:
        enabled: true
    config:
      discovery:
        enabled: true
        service-id: config-server
  config:
    import: optional:configserver:config-server
management:
  endpoints:
    web:
      exposure:
        include: "prometheus,health,info"
  endpoint:
    health:
      show-details: always