spring:
  application:
    name: book-service
  datasource:
    url: jdbc:postgresql://postgres:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
#        connection.pool_size: 20
#        jdbc.batch_size: 20
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: book_group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always


  #  liquibase:
  #    change-log: classpath:/db/changelog/db.changelog-master.xml
  #  liquibase:
  #    enabled: false
logging:
  level:
    org.springframework.boot: DEBUG
    org.springframework.jdbc.datasource: DEBUG